"""Hand-crafted realistic-ish mock findings per AI-infrastructure component.

For each company: market position, financials (P/E trailing & forward, EV/EBITDA,
analyst consensus, price targets), our recommendation, thesis, and risks.

This powers Demo mode. Numbers are PLAUSIBLE and illustrative — directionally
correct as of May 2026 but NOT real-time. Live Gemini/Claude runs override this
with researched data. NOT investment advice.
"""
from __future__ import annotations

# ---------- helpers ----------

def _co(
    name, *, ticker=None, public=True, hq="United States",
    share_pct=None, bucket=None, sole=False, moats=None,
    switching=None, customer=None, demand=None, val=None, notes=None,
    structure=None, supply="constrained",
    price=None, mcap=None,
    pe_t=None, pe_f=None, peg=None, ev_ebitda=None, ev_sales=None,
    rev_ttm=None, rev_fwd=None, op_mgn=None, fcf_y=None, div_y=None, beta=None,
    high52=None, low52=None,
    buy=None, hold=None, sell=None, pt_low=None, pt_avg=None, pt_high=None,
    rec=None, conviction=None, exp_ret=None, bull=None, base=None, bear=None,
    thesis_summary=None, thesis=None, risks=None, catalysts=None,
):
    return {
        "name": name, "ticker": ticker, "is_public": public, "hq_country": hq,
        "market_share_pct": share_pct, "market_share_bucket": bucket,
        "single_source": sole, "moat_types": moats or [],
        "switching_costs": switching, "customer_concentration": customer,
        "demand_signal": demand, "valuation_usd": val, "notes": notes,
        "extras": {
            "structure": structure, "supply_status": supply,
            "stock_price": price, "market_cap_usd": mcap,
            "pe_trailing": pe_t, "pe_forward": pe_f, "peg": peg,
            "ev_ebitda": ev_ebitda, "ev_sales": ev_sales,
            "revenue_growth_ttm": rev_ttm, "revenue_growth_fwd": rev_fwd,
            "operating_margin": op_mgn, "fcf_yield": fcf_y, "dividend_yield": div_y,
            "beta": beta, "week52_high": high52, "week52_low": low52,
            "analyst_buy": buy, "analyst_hold": hold, "analyst_sell": sell,
            "price_target_low": pt_low, "price_target_avg": pt_avg, "price_target_high": pt_high,
            "recommendation": rec, "conviction": conviction, "expected_return_12m": exp_ret,
            "bull_target": bull, "base_target": base, "bear_target": bear,
            "thesis_summary": thesis_summary,
            "thesis_points": thesis or [], "risks": risks or [], "catalysts": catalysts or [],
        },
    }


# ---------- per-component findings ----------

MOCK_FINDINGS: dict[str, list[dict]] = {

    # ===== Tier 0: Raw materials =====

    "Copper": [
        _co("Freeport-McMoRan", ticker="FCX", share_pct=8, bucket="<10",
            moats=["scale"], demand="AI datacenter + grid buildout = +1-2 Mt incremental demand by 2030",
            structure="fragmented", supply="constrained",
            price=48, mcap=70_000_000_000, pe_t=22, pe_f=15, peg=0.9,
            ev_ebitda=9.5, ev_sales=2.6, rev_ttm=0.08, rev_fwd=0.14,
            op_mgn=0.24, fcf_y=0.045, div_y=0.012, beta=1.7,
            high52=55, low52=36, buy=18, hold=8, sell=1,
            pt_low=40, pt_avg=58, pt_high=72, rec="STRONG_BUY", conviction="HIGH", exp_ret=0.30,
            bull=72, base=58, bear=42,
            thesis_summary="Highest-leverage public play on AI datacenter copper demand; long-life Grasberg + Arizona assets.",
            thesis=[
                "Best operating leverage to LME copper price among large miners",
                "AI datacenter buildout is the swing factor on the global copper deficit through 2030",
                "Grasberg expansion adds low-cost ounces with rebated gold credits",
                "Capital discipline + buyback program = double-digit FCF yield at $5+/lb copper",
            ],
            risks=[
                "Cyclical exposure; commodity price drives 80% of variance",
                "Indonesia royalty/permit risk on Grasberg",
                "Substitution risk (aluminum) at >$5/lb copper",
            ],
            catalysts=[
                "Q3 production update (potential beat from El Abra restart)",
                "Multi-year copper supply deficit forecast updates from CRU/Wood Mackenzie",
                "Datacenter capex guidance from hyperscalers (next earnings cycle)",
            ]),
        _co("Southern Copper", ticker="SCCO", share_pct=6, bucket="<10",
            moats=["scale"], demand="strong - Peru + Mexico expansions",
            structure="fragmented", supply="constrained",
            price=115, mcap=89_000_000_000, pe_t=24, pe_f=18, peg=1.1,
            ev_ebitda=11, ev_sales=8, rev_ttm=0.11, rev_fwd=0.12,
            op_mgn=0.48, fcf_y=0.035, div_y=0.045, beta=1.2,
            high52=130, low52=90, buy=8, hold=12, sell=2,
            pt_low=95, pt_avg=120, pt_high=145, rec="BUY", conviction="MEDIUM", exp_ret=0.12,
            bull=145, base=120, bear=92,
            thesis_summary="Lowest-cost copper producer globally with multi-decade reserve life and high dividend.",
            thesis=[
                "Lowest cash cost per ton in the majors universe",
                "Tia Maria + Los Chancas projects bring ~300kt new supply 2027+",
                "Capital allocation skewed to dividends (4.5% yield)",
            ],
            risks=["Peru regulatory/political risk on Tia Maria approval", "Single-region concentration"],
            catalysts=["Tia Maria EIA approval", "Buenavista expansion ramp"]),
        _co("BHP Group", ticker="BHP", hq="Australia", share_pct=4, bucket="<10",
            moats=["scale"], demand="diversified - copper + iron + potash",
            structure="fragmented", supply="balanced",
            price=58, mcap=145_000_000_000, pe_t=14, pe_f=12, peg=1.3,
            ev_ebitda=6.5, ev_sales=3.4, rev_ttm=0.03, rev_fwd=0.05,
            op_mgn=0.36, fcf_y=0.07, div_y=0.052, beta=0.9,
            high52=64, low52=46, buy=12, hold=14, sell=3,
            pt_low=52, pt_avg=63, pt_high=72, rec="HOLD", conviction="MEDIUM", exp_ret=0.09,
            bull=72, base=63, bear=50,
            thesis_summary="Diversified miner — copper exposure is real but diluted by iron ore beta.",
            thesis=["Escondida is the world's largest copper mine", "Strong balance sheet, conservative capital allocation"],
            risks=["Iron ore overhang dominates near-term P&L", "Capital allocation discipline could constrain growth"],
            catalysts=["Copper-divestiture spin-off speculation"]),
    ],

    "Rare Earths & Specialty Metals": [
        _co("MP Materials", ticker="MP", share_pct=15, bucket="10-25",
            moats=["regulatory", "scale"],
            demand="strong - Western diversification mandate, DoD contracts",
            structure="oligopoly", supply="constrained",
            price=22, mcap=3_700_000_000, pe_t=None, pe_f=42, peg=2.5,
            ev_ebitda=18, ev_sales=12, rev_ttm=0.45, rev_fwd=0.65,
            op_mgn=0.05, fcf_y=-0.04, div_y=0, beta=2.1,
            high52=28, low52=12, buy=8, hold=4, sell=1,
            pt_low=18, pt_avg=27, pt_high=38, rec="STRONG_BUY", conviction="HIGH", exp_ret=0.35,
            bull=42, base=30, bear=18,
            thesis_summary="Only fully-integrated rare-earth processor outside China; structural China-decoupling tailwind.",
            thesis=[
                "Sole at-scale rare-earth processor in the Western hemisphere",
                "DoD price-floor contract de-risks downside",
                "Mountain Pass + Fort Worth magnet plant = vertical integration finishing 2026",
                "Geopolitical China-export-restriction tailwind on neodymium & dysprosium",
            ],
            risks=[
                "China can flood market to suppress prices and break Western capex thesis",
                "Magnet plant ramp execution risk",
                "Customer concentration during ramp-up phase",
            ],
            catalysts=[
                "Magnet plant first revenue (Q2 2026)",
                "Auto OEM long-term offtake agreements",
                "Further DoD funding tranches",
            ]),
        _co("Lynas Rare Earths", ticker="LYC.AX", hq="Australia",
            share_pct=12, bucket="10-25",
            moats=["regulatory"], demand="long-term offtake to Japan",
            structure="oligopoly", supply="constrained",
            price=7.2, mcap=6_800_000_000, pe_t=35, pe_f=22, peg=1.8,
            ev_ebitda=14, ev_sales=8, rev_ttm=0.18, rev_fwd=0.32,
            op_mgn=0.22, fcf_y=0.02, div_y=0, beta=1.6,
            high52=8.5, low52=5.1, buy=9, hold=5, sell=2,
            pt_low=6.5, pt_avg=8.2, pt_high=11, rec="BUY", conviction="MEDIUM", exp_ret=0.18,
            bull=11, base=8.2, bear=6,
            thesis_summary="Second-largest non-Chinese rare-earth producer; Texas plant adds US capacity.",
            thesis=["Long-term offtake with Japanese consortium", "Kalgoorlie + Mt Weld expansion ramp"],
            risks=["Pricing volatility tied to Chinese policy", "Texas plant cost overrun risk"],
            catalysts=["Texas plant commissioning 2026"]),
        _co("China Northern Rare Earth", ticker="600111.SS", hq="China",
            share_pct=42, bucket="25-50", moats=["scale", "regulatory"],
            demand="captive Chinese demand + export quotas",
            structure="oligopoly", supply="balanced",
            mcap=20_000_000_000,
            rec="HOLD", conviction="LOW", exp_ret=0.05,
            thesis_summary="Largest global producer but China access/geopolitical risk caps Western investor appeal.",
            risks=["China regulatory risk for foreign investors", "Export quota policy volatility"]),
    ],

    "Industrial Gases": [
        _co("Linde", ticker="LIN", hq="Ireland", share_pct=35, bucket="25-50",
            moats=["scale", "switching_costs"],
            switching="very high - on-site plants + long-term contracts",
            demand="strong - semi fab buildout demand",
            structure="oligopoly", supply="balanced",
            price=475, mcap=225_000_000_000, pe_t=32, pe_f=27, peg=2.4,
            ev_ebitda=18, ev_sales=6.5, rev_ttm=0.06, rev_fwd=0.09,
            op_mgn=0.27, fcf_y=0.034, div_y=0.013, beta=0.85,
            high52=510, low52=400, buy=21, hold=6, sell=0,
            pt_low=480, pt_avg=540, pt_high=600, rec="BUY", conviction="HIGH", exp_ret=0.18,
            bull=600, base=540, bear=460,
            thesis_summary="Defensive AI-infra play: every fab needs industrial gases; long-term contracts insulate from cycles.",
            thesis=[
                "Largest industrial gas company globally with scale + density advantages",
                "Long-term take-or-pay contracts (avg 15+ years) provide annuity-like cash flow",
                "Semi fab buildout adds ~$5B in contracted backlog over 5 years",
                "Hydrogen energy transition is optional upside (10x scale by 2035)",
            ],
            risks=["Cyclical exposure to industrial activity (~30% of revenue)", "Helium price volatility"],
            catalysts=["Major fab contract wins (TSMC AZ, Samsung TX)", "Hydrogen project FIDs"]),
        _co("Air Products", ticker="APD", share_pct=22, bucket="10-25",
            moats=["scale", "switching_costs"], switching="high - on-site plants",
            demand="strong - hydrogen + semis", structure="oligopoly",
            price=290, mcap=64_000_000_000, pe_t=24, pe_f=20, peg=2.0,
            ev_ebitda=14, ev_sales=5.2, rev_ttm=0.04, rev_fwd=0.07,
            op_mgn=0.22, fcf_y=0.03, div_y=0.025, beta=0.7,
            high52=320, low52=240, buy=12, hold=10, sell=2,
            pt_low=270, pt_avg=315, pt_high=360, rec="BUY", conviction="MEDIUM", exp_ret=0.12,
            bull=360, base=315, bear=250,
            thesis_summary="#2 industrial gas with strong hydrogen positioning but execution risk on mega-projects.",
            thesis=["NEOM hydrogen mega-project = optionality", "Strong dividend track record"],
            risks=["NEOM project execution + funding risk", "Capital intensity higher than peers"],
            catalysts=["NEOM milestone update"]),
        _co("Air Liquide", ticker="AI.PA", hq="France", share_pct=18, bucket="10-25",
            moats=["scale"], demand="strong", structure="oligopoly",
            price=175, mcap=105_000_000_000, pe_t=29, pe_f=24, peg=2.3,
            ev_ebitda=15, ev_sales=4.8, rev_ttm=0.05, rev_fwd=0.08,
            op_mgn=0.18, fcf_y=0.028, div_y=0.019, beta=0.75,
            high52=190, low52=150, buy=14, hold=10, sell=1,
            pt_low=170, pt_avg=195, pt_high=220, rec="BUY", conviction="MEDIUM", exp_ret=0.14,
            thesis_summary="European industrial gas leader; electronics segment adds AI exposure.",
            thesis=["Diversified geographic mix lowers cyclicality", "Electronics segment is 15% but fastest growing"],
            risks=["European industrial slowdown drag"],
            catalysts=["Electronics segment investor day"]),
    ],

    "Specialty Semiconductor Chemicals": [
        _co("Shin-Etsu Chemical", ticker="4063.T", hq="Japan",
            share_pct=30, bucket="25-50", moats=["ip", "scale", "process"],
            switching="very high - qualified at every fab",
            demand="constrained - photoresist supply tight",
            structure="oligopoly", supply="constrained",
            price=42, mcap=80_000_000_000, pe_t=18, pe_f=16, peg=1.4,
            ev_ebitda=10, ev_sales=3.4, rev_ttm=0.08, rev_fwd=0.11,
            op_mgn=0.28, fcf_y=0.055, div_y=0.018, beta=0.95,
            high52=48, low52=34, buy=18, hold=4, sell=0,
            pt_low=42, pt_avg=52, pt_high=62, rec="STRONG_BUY", conviction="HIGH", exp_ret=0.24,
            bull=62, base=52, bear=40,
            thesis_summary="Sole-source-class supplier of EUV photoresist + silicon wafers; an irreplaceable AI-fab vendor.",
            thesis=[
                "Effectively sole-source for the highest-end EUV photoresist (>80% share)",
                "Largest silicon wafer producer globally",
                "Margins among best in chemicals; capital discipline + buybacks",
                "Yen weakness is a tailwind for export competitiveness",
            ],
            risks=["Japan-specific concentration", "Photoresist supply disruption (earthquake, geopolitics)"],
            catalysts=["TSMC + Samsung Arizona fab ramps", "Capacity expansion announcements"]),
        _co("JSR Corporation", ticker="4185.T", hq="Japan",
            share_pct=22, bucket="10-25", moats=["ip", "process"],
            switching="high", demand="strong",
            structure="oligopoly",
            price=28, mcap=6_500_000_000, pe_t=22, pe_f=18, peg=1.6,
            ev_ebitda=11, ev_sales=2.2, rev_ttm=0.07, rev_fwd=0.10,
            op_mgn=0.16, fcf_y=0.04, div_y=0.025, beta=1.1,
            high52=32, low52=22, buy=8, hold=6, sell=1,
            pt_low=26, pt_avg=33, pt_high=40, rec="BUY", conviction="MEDIUM", exp_ret=0.18,
            thesis_summary="Pure-play EUV photoresist beneficiary; recently taken private by JIC then re-listed.",
            thesis=["EUV photoresist is highest-margin product line", "JIC backing provides capex flexibility"],
            risks=["Customer concentration (TSMC, Samsung, Intel = 70% of EUV resist)"],
            catalysts=["EUV resist volume ramp"]),
        _co("Entegris", ticker="ENTG", share_pct=18, bucket="10-25",
            moats=["tech", "ip"], demand="strong - leading-edge fab spend",
            structure="oligopoly",
            price=145, mcap=21_500_000_000, pe_t=42, pe_f=28, peg=2.0,
            ev_ebitda=22, ev_sales=4.5, rev_ttm=0.09, rev_fwd=0.16,
            op_mgn=0.19, fcf_y=0.025, div_y=0.006, beta=1.3,
            high52=160, low52=110, buy=15, hold=5, sell=0,
            pt_low=140, pt_avg=170, pt_high=200, rec="BUY", conviction="HIGH", exp_ret=0.22,
            bull=200, base=170, bear=130,
            thesis_summary="High-purity materials + filtration; deeply embedded across the entire AI fab supply chain.",
            thesis=["High-purity content per wafer rises with node shrink", "CMC Materials acquisition expanded TAM"],
            risks=["Debt load from CMC deal", "Cyclical fab capex exposure"],
            catalysts=["Margin recovery from deleveraging", "Advanced packaging materials growth"]),
    ],

    "Chip Substrates (ABF)": [
        _co("Ibiden", ticker="4062.T", hq="Japan", share_pct=42, bucket="25-50",
            moats=["process", "scale", "ip"], switching="very high",
            demand="constrained - ABF capacity tight for AI accelerators",
            structure="oligopoly", supply="constrained",
            price=65, mcap=9_500_000_000, pe_t=14, pe_f=11, peg=0.9,
            ev_ebitda=7, ev_sales=2.1, rev_ttm=0.12, rev_fwd=0.18,
            op_mgn=0.16, fcf_y=0.07, div_y=0.013, beta=1.2,
            high52=78, low52=48, buy=12, hold=6, sell=1,
            pt_low=60, pt_avg=80, pt_high=98, rec="STRONG_BUY", conviction="HIGH", exp_ret=0.32,
            bull=98, base=80, bear=58,
            thesis_summary="Dominant ABF substrate supplier; NVIDIA's biggest unhedged supply chain bottleneck after CoWoS.",
            thesis=[
                "Largest ABF substrate producer; NVIDIA's primary qualified vendor",
                "Substrate capacity additions take 2+ years to bring online",
                "Higher layer counts (>20L) compound pricing power",
                "Trades at half the multiple of comparable AI-supply-chain names",
            ],
            risks=["Customer concentration (Intel + NVIDIA = >50% of substrate revenue)", "Capacity-induced ASP pressure"],
            catalysts=["ABF capacity expansion announcements", "Improved package-substrate pricing in Q3"]),
        _co("Unimicron", ticker="3037.TW", hq="Taiwan",
            share_pct=18, bucket="10-25", moats=["scale"],
            demand="strong", structure="oligopoly",
            price=4.2, mcap=6_800_000_000, pe_t=22, pe_f=15, peg=1.2,
            ev_ebitda=9, ev_sales=2.8, rev_ttm=0.08, rev_fwd=0.14,
            op_mgn=0.11, fcf_y=0.045, div_y=0.022, beta=1.4,
            high52=4.8, low52=3.0, buy=8, hold=8, sell=2,
            pt_low=3.8, pt_avg=4.8, pt_high=5.8, rec="BUY", conviction="MEDIUM", exp_ret=0.14,
            thesis_summary="#2 ABF substrate maker; TSMC-adjacent location is a structural advantage.",
            thesis=["Taiwan adjacency to TSMC + customers", "ABF capacity expansion underway"],
            risks=["Geopolitical concentration", "Pricing power weaker than #1 player"],
            catalysts=["AI substrate qualification wins"]),
        _co("Shinko Electric", ticker="6967.T", hq="Japan",
            share_pct=15, bucket="10-25", moats=["process"],
            demand="strong", structure="oligopoly",
            price=72, mcap=4_500_000_000, pe_t=18, pe_f=14, peg=1.1,
            ev_ebitda=8, ev_sales=2.4, rev_ttm=0.06, rev_fwd=0.10,
            op_mgn=0.14, fcf_y=0.04, div_y=0.025, beta=1.0,
            high52=80, low52=55, buy=6, hold=10, sell=1,
            pt_low=68, pt_avg=82, pt_high=95, rec="HOLD", conviction="MEDIUM", exp_ret=0.10,
            thesis_summary="ABF substrate specialist; consider as a hedged pairs trade with Ibiden.",
            risks=["Smaller scale limits margin"], catalysts=["FPGA/networking substrate growth"]),
    ],

    "Datacenter Water Infrastructure": [
        _co("Xylem", ticker="XYL", share_pct=18, bucket="10-25", moats=["scale"],
            demand="strong - datacenter water reuse mandate",
            structure="fragmented",
            price=132, mcap=32_000_000_000, pe_t=32, pe_f=26, peg=2.4,
            ev_ebitda=18, ev_sales=4.2, rev_ttm=0.06, rev_fwd=0.09,
            op_mgn=0.15, fcf_y=0.025, div_y=0.010, beta=1.0,
            high52=145, low52=100, buy=14, hold=6, sell=0,
            pt_low=130, pt_avg=150, pt_high=175, rec="BUY", conviction="MEDIUM", exp_ret=0.16,
            thesis_summary="Water infrastructure benefits from datacenter cooling + reuse + ESG requirements.",
            thesis=["Evoqua acquisition adds industrial water treatment scale", "Datacenter cooling is fastest-growing end-market"],
            risks=["Capex cycle dependency"], catalysts=["Datacenter water-reuse contracts"]),
        _co("Pentair", ticker="PNR", share_pct=8, bucket="<10", moats=["scale"],
            demand="growing", structure="fragmented",
            price=98, mcap=16_000_000_000, pe_t=22, pe_f=18, peg=1.5,
            ev_ebitda=15, ev_sales=2.4, rev_ttm=0.04, rev_fwd=0.07,
            op_mgn=0.17, fcf_y=0.04, div_y=0.019, beta=1.1,
            buy=10, hold=8, sell=1, pt_low=95, pt_avg=110, pt_high=125,
            rec="HOLD", conviction="LOW", exp_ret=0.12),
    ],

    # ===== Tier 1: Semiconductor capex =====

    "EUV Lithography": [
        _co("ASML Holding", ticker="ASML", hq="Netherlands",
            share_pct=100, bucket="sole", sole=True,
            moats=["ip", "regulatory", "scale", "process"],
            switching="very high lock-in (decade-long install + training)",
            customer="TSMC, Samsung, Intel = >85% of revenue",
            demand="exponential growth, multi-year backlog into 2028+",
            val=380_000_000_000,
            structure="monopoly", supply="constrained",
            price=950, mcap=380_000_000_000, pe_t=40, pe_f=28, peg=1.4,
            ev_ebitda=25, ev_sales=11, rev_ttm=0.28, rev_fwd=0.32,
            op_mgn=0.32, fcf_y=0.024, div_y=0.008, beta=1.15,
            high52=1100, low52=600, buy=28, hold=4, sell=1,
            pt_low=850, pt_avg=1150, pt_high=1300,
            rec="STRONG_BUY", conviction="HIGH", exp_ret=0.25,
            bull=1400, base=1200, bear=900,
            thesis_summary="The single most defensible monopoly in tech. No competitor before 2030+. Buy on any pullback.",
            thesis=[
                "Sole-source for EUV scanners — no commercial alternative this decade",
                "High-NA EUV at $400M+ per system; 2nd-gen monopoly already locked in",
                "Customer concentration is a feature, not a bug — only 3 customers exist",
                "Service & upgrades = recurring revenue stream (~30% of sales) growing faster than systems",
                "Export-control risk to China is already in price; Western fab spend more than offsets",
            ],
            risks=[
                "China export controls expand further (cuts ~15% of revenue)",
                "Customer capex digestion creates 1-2 quarter air pockets",
                "Cyclical, not secular, demand smoothing requires patience on quarters",
            ],
            catalysts=[
                "High-NA EUV order book updates (2026 deliveries)",
                "TSMC + Samsung CapEx guidance revisions",
                "China license clarifications",
            ]),
        _co("Carl Zeiss SMT", public=False, hq="Germany",
            share_pct=100, bucket="sole", sole=True,
            moats=["ip", "process", "scale"],
            switching="lock-in", demand="tied to ASML capacity expansion",
            structure="monopoly", supply="constrained",
            notes="Private subsidiary of Zeiss group. Sole supplier of EUV optics to ASML.",
            rec="N/A", conviction="N/A",
            thesis_summary="Private monopoly — no direct equity access. Exposure via Zeiss parent or ASML beta."),
    ],

    "Leading-edge Foundry": [
        _co("TSMC", ticker="TSM", hq="Taiwan", share_pct=92, bucket=">75",
            moats=["scale", "process", "ip"],
            switching="high - process libraries are not portable",
            customer="Apple ~25%, NVIDIA ~10%, AMD ~7%",
            demand="shortage of CoWoS capacity; pricing power",
            val=850_000_000_000,
            structure="oligopoly", supply="constrained",
            price=175, mcap=900_000_000_000, pe_t=28, pe_f=20, peg=0.9,
            ev_ebitda=15, ev_sales=9, rev_ttm=0.24, rev_fwd=0.28,
            op_mgn=0.43, fcf_y=0.045, div_y=0.013, beta=1.1,
            high52=205, low52=130, buy=42, hold=6, sell=1,
            pt_low=180, pt_avg=220, pt_high=270,
            rec="STRONG_BUY", conviction="HIGH", exp_ret=0.30,
            bull=270, base=220, bear=160,
            thesis_summary=">90% share at leading edge with structural pricing power. Geopolitical discount is the alpha.",
            thesis=[
                ">90% leading-edge logic share; pricing power on 3nm and below",
                "CoWoS bottleneck creates pricing leverage on all AI accelerators",
                "Arizona + Japan + Germany diversification de-risks Taiwan geopolitical premium",
                "Free cash flow inflection as capex peaks in 2025",
                "Trades at half the multiple of NVIDIA despite being the upstream bottleneck",
            ],
            risks=[
                "Taiwan geopolitical premium (most-priced-in but real)",
                "Capex digestion risk if AI demand pauses",
                "Customer concentration in Apple + NVIDIA",
            ],
            catalysts=[
                "CoWoS capacity expansion announcements",
                "Arizona fab production milestone",
                "2nm process customer wins",
            ]),
        _co("Samsung Foundry", ticker="005930.KS", hq="South Korea",
            share_pct=7, bucket="<10", moats=["scale"],
            demand="stable but losing share at leading edge",
            structure="oligopoly", supply="balanced",
            price=58, mcap=380_000_000_000, pe_t=14, pe_f=11, peg=1.6,
            ev_ebitda=4.5, ev_sales=1.3, rev_ttm=0.04, rev_fwd=0.10,
            op_mgn=0.12, fcf_y=0.06, div_y=0.025, beta=1.0,
            buy=18, hold=14, sell=2, pt_low=55, pt_avg=70, pt_high=90,
            rec="HOLD", conviction="LOW", exp_ret=0.08,
            thesis_summary="Bundled foundry + HBM + DRAM play; foundry side has 3nm yield issues.",
            risks=["3nm yield issues", "Distant #2 in leading edge"]),
        _co("Intel Foundry", ticker="INTC", share_pct=1, bucket="<10",
            moats=["scale"], demand="ramping - 18A node bet",
            structure="oligopoly",
            price=32, mcap=140_000_000_000, pe_t=None, pe_f=24, peg=None,
            ev_ebitda=12, ev_sales=2.3, rev_ttm=-0.05, rev_fwd=0.08,
            op_mgn=-0.04, fcf_y=-0.03, div_y=0, beta=1.4,
            buy=8, hold=20, sell=8, pt_low=24, pt_avg=33, pt_high=44,
            rec="HOLD", conviction="LOW", exp_ret=0.08,
            thesis_summary="Long-shot turnaround on 18A node; needs major customer win to validate."),
    ],

    "AI Accelerator Silicon": [
        _co("NVIDIA", ticker="NVDA", share_pct=86, bucket=">75",
            moats=["ip", "scale", "tech"],
            switching="very high - CUDA ecosystem lock-in",
            customer="hyperscalers + neoclouds dominate orders",
            demand="accelerating, backlog into 2026", val=3_200_000_000_000,
            structure="oligopoly", supply="constrained",
            price=140, mcap=3_400_000_000_000, pe_t=50, pe_f=32, peg=0.8,
            ev_ebitda=42, ev_sales=22, rev_ttm=0.85, rev_fwd=0.55,
            op_mgn=0.55, fcf_y=0.028, div_y=0.003, beta=1.6,
            high52=155, low52=85, buy=58, hold=8, sell=2,
            pt_low=125, pt_avg=170, pt_high=220,
            rec="BUY", conviction="HIGH", exp_ret=0.20,
            bull=220, base=170, bear=110,
            thesis_summary="Best-in-class growth + CUDA moat. Priced for perfection, but earnings revisions still trending up.",
            thesis=[
                "CUDA software ecosystem is the deepest moat in tech",
                "Annual cadence (Blackwell -> Rubin) maintains 18-month performance lead",
                "Networking + software pulling 2x weight in revenue mix",
                "Sovereign AI orders add new demand vector beyond hyperscalers",
            ],
            risks=[
                "Hyperscaler custom silicon (TPU, Trainium, Maia) takes 10-15% by 2027",
                "Valuation leaves little margin for execution misstep",
                "China revenue cap from export controls",
            ],
            catalysts=["Rubin platform reveal", "Sovereign AI contract announcements", "Networking attach rate"]),
        _co("AMD", ticker="AMD", share_pct=9, bucket="<10",
            moats=["tech"], switching="medium - ROCm narrowing the gap",
            demand="growing customer pipeline (Meta, MS)",
            structure="oligopoly", supply="balanced",
            price=165, mcap=270_000_000_000, pe_t=58, pe_f=28, peg=1.0,
            ev_ebitda=32, ev_sales=10, rev_ttm=0.22, rev_fwd=0.45,
            op_mgn=0.18, fcf_y=0.018, div_y=0, beta=1.7,
            high52=210, low52=130, buy=32, hold=14, sell=1,
            pt_low=150, pt_avg=210, pt_high=275,
            rec="BUY", conviction="MEDIUM", exp_ret=0.27,
            bull=275, base=210, bear=140,
            thesis_summary="Credible #2 in AI silicon. MI400 platform is the catalyst; valuation has room to re-rate.",
            thesis=[
                "MI300/MI325/MI400 cadence closing gap with NVIDIA",
                "Meta + Microsoft are reference customers for inference",
                "ROCm ecosystem improving; Hugging Face + PyTorch coverage growing",
                "EPYC server share still expanding alongside",
            ],
            risks=["NVIDIA software lead is structural", "Margin dilution from low-margin chiplets"],
            catalysts=["MI400 launch", "Hyperscaler design wins"]),
        _co("Google TPU", ticker="GOOGL", share_pct=4, bucket="<10",
            moats=["ip", "tech"], demand="strong internal demand",
            structure="oligopoly",
            price=185, mcap=2_300_000_000_000, pe_t=24, pe_f=20, peg=1.4,
            ev_ebitda=15, ev_sales=6, rev_ttm=0.12, rev_fwd=0.13,
            op_mgn=0.31, fcf_y=0.038, div_y=0.005, beta=1.05,
            buy=44, hold=8, sell=1, pt_low=180, pt_avg=215, pt_high=255,
            rec="BUY", conviction="HIGH", exp_ret=0.22,
            bull=255, base=215, bear=170,
            thesis_summary="TPU is captive; the play is Google parent benefitting from internal cost advantage + GCP rental.",
            thesis=["TPU lowers Google's effective cost of training", "Search + YouTube AI monetization", "GCP gains share in AI workloads"],
            risks=["Antitrust pressure on Search", "Capex outpacing FCF"]),
    ],

    "High-Bandwidth Memory (HBM)": [
        _co("SK Hynix", ticker="000660.KS", hq="South Korea",
            share_pct=53, bucket="50-75", moats=["process", "scale", "ip"],
            switching="high - qualified by NVIDIA on HBM3E",
            customer="NVIDIA is >40% of HBM bookings",
            demand="shortage through 2026, all capacity sold out",
            val=115_000_000_000,
            structure="oligopoly", supply="constrained",
            price=180, mcap=135_000_000_000, pe_t=9, pe_f=7, peg=0.4,
            ev_ebitda=5, ev_sales=2.5, rev_ttm=0.32, rev_fwd=0.45,
            op_mgn=0.35, fcf_y=0.065, div_y=0.012, beta=1.3,
            high52=210, low52=120, buy=34, hold=4, sell=0,
            pt_low=190, pt_avg=240, pt_high=300,
            rec="STRONG_BUY", conviction="HIGH", exp_ret=0.33,
            bull=300, base=240, bear=170,
            thesis_summary="HBM3E first-mover with NVIDIA-locked supply. Multi-year pricing power; trades at 7x forward earnings.",
            thesis=[
                "First-to-volume on HBM3E with NVIDIA qualification",
                "Three-supplier oligopoly with discipline = sustained pricing",
                "All HBM capacity sold out through 2026; pricing locked in",
                "DRAM upcycle adds optionality beyond HBM",
                "Trades at half multiple of US semis with better growth",
            ],
            risks=[
                "DRAM cycle eventual rollover",
                "Samsung HBM3E qualification at NVIDIA tightens supply share",
                "Korea won FX volatility",
            ],
            catalysts=["HBM4 leadership announcement", "DRAM ASP guidance"]),
        _co("Samsung Memory", ticker="005930.KS", hq="South Korea",
            share_pct=38, bucket="25-50", moats=["scale", "process"],
            switching="high", demand="strong; behind on HBM3E qual",
            structure="oligopoly",
            buy=18, hold=12, sell=2, pt_low=55, pt_avg=70, pt_high=90,
            rec="HOLD", conviction="MEDIUM", exp_ret=0.10,
            thesis_summary="HBM3E qualification timing at NVIDIA is the swing factor; awaiting catalyst."),
        _co("Micron", ticker="MU", share_pct=9, bucket="<10",
            moats=["process"], switching="medium",
            demand="ramping; 2026 capacity full",
            structure="oligopoly", supply="constrained",
            price=145, mcap=160_000_000_000, pe_t=22, pe_f=10, peg=0.4,
            ev_ebitda=9, ev_sales=4.2, rev_ttm=0.55, rev_fwd=0.32,
            op_mgn=0.28, fcf_y=0.025, div_y=0.005, beta=1.4,
            high52=175, low52=85, buy=30, hold=6, sell=1,
            pt_low=140, pt_avg=180, pt_high=220,
            rec="BUY", conviction="HIGH", exp_ret=0.24,
            bull=220, base=180, bear=120,
            thesis_summary="Third HBM supplier with US-listed access; CHIPS Act subsidies de-risk capex.",
            thesis=["Only US-domiciled HBM player", "CHIPS Act funding reduces capex burden", "Cycle leverage on DRAM upturn"],
            risks=["Smallest HBM share; capacity ramp execution"],
            catalysts=["HBM4 sampling milestones"]),
    ],

    "Advanced Packaging (CoWoS / SoIC)": [
        _co("TSMC (CoWoS)", ticker="TSM", hq="Taiwan",
            share_pct=88, bucket=">75", moats=["process", "scale", "ip"],
            switching="very high - the binding constraint on AI buildout",
            customer="NVIDIA absorbs majority of capacity",
            demand="shortage; capacity 2x'ing but still oversold",
            structure="oligopoly", supply="constrained",
            notes="See TSM main listing — CoWoS is the binding constraint on AI accelerator shipments.",
            rec="SEE_TSM", conviction="HIGH",
            thesis_summary="CoWoS capacity is the actual physical bottleneck for AI accelerators. Buy TSM."),
        _co("Amkor Technology", ticker="AMKR", share_pct=6, bucket="<10",
            moats=["scale"], demand="growing as 2nd source",
            structure="oligopoly",
            price=32, mcap=8_000_000_000, pe_t=18, pe_f=14, peg=1.1,
            ev_ebitda=8, ev_sales=1.3, rev_ttm=0.06, rev_fwd=0.12,
            op_mgn=0.10, fcf_y=0.05, div_y=0.025, beta=1.3,
            high52=42, low52=24, buy=10, hold=8, sell=1,
            pt_low=30, pt_avg=42, pt_high=55, rec="BUY", conviction="MEDIUM", exp_ret=0.31,
            bull=55, base=42, bear=28,
            thesis_summary="2nd-source advanced packaging; Arizona ramp aligns with TSMC + customers re-shoring.",
            thesis=["Arizona facility co-located with TSMC AZ", "OSAT consolidation tailwind"],
            risks=["Concentrated customer base"]),
    ],

    "Datacenter Networking Silicon": [
        _co("Broadcom", ticker="AVGO", share_pct=62, bucket="50-75",
            moats=["ip", "scale", "tech"],
            switching="high - custom ASIC partnerships with hyperscalers",
            customer="Google, Meta, Apple AI silicon partners",
            demand="+50% YoY AI networking revenue", val=850_000_000_000,
            structure="oligopoly", supply="balanced",
            price=210, mcap=1_000_000_000_000, pe_t=38, pe_f=28, peg=1.1,
            ev_ebitda=25, ev_sales=18, rev_ttm=0.42, rev_fwd=0.22,
            op_mgn=0.45, fcf_y=0.035, div_y=0.012, beta=1.2,
            high52=240, low52=140, buy=36, hold=4, sell=0,
            pt_low=205, pt_avg=255, pt_high=310,
            rec="STRONG_BUY", conviction="HIGH", exp_ret=0.21,
            bull=310, base=255, bear=180,
            thesis_summary="The pure-play on hyperscaler custom AI silicon + networking. Software + cash discipline = compounder.",
            thesis=[
                "Custom AI silicon for Google, Meta, others = recurring annuity",
                "Tomahawk + Jericho switch ASICs dominate AI fabric",
                "VMware integration unlocks software FCF",
                "Capital return discipline (dividends + buybacks)",
            ],
            risks=["Customer-controlled ASIC roadmaps", "VMware integration execution"],
            catalysts=["Hyperscaler design win announcements", "VMware ARR milestones"]),
        _co("Marvell", ticker="MRVL", share_pct=9, bucket="<10",
            moats=["tech"], demand="Amazon custom silicon partnership ramping",
            structure="oligopoly",
            price=88, mcap=76_000_000_000, pe_t=None, pe_f=32, peg=1.3,
            ev_ebitda=28, ev_sales=12, rev_ttm=0.18, rev_fwd=0.35,
            op_mgn=0.12, fcf_y=0.022, div_y=0.003, beta=1.5,
            high52=110, low52=58, buy=24, hold=6, sell=0,
            pt_low=90, pt_avg=115, pt_high=145,
            rec="BUY", conviction="HIGH", exp_ret=0.30,
            bull=145, base=115, bear=72,
            thesis_summary="AWS custom Trainium silicon partner; the cleanest pure-play hyperscaler ASIC name.",
            thesis=["AWS Trainium2/3 ramp", "Optical DSP leadership", "Pure-play AI vs Broadcom's diversified mix"],
            risks=["Customer concentration on AWS"]),
    ],

    "Optical Interconnect / Transceivers": [
        _co("Coherent", ticker="COHR", share_pct=28, bucket="25-50",
            moats=["ip", "scale"], demand="800G ramp accelerating",
            structure="oligopoly",
            price=85, mcap=13_000_000_000, pe_t=42, pe_f=22, peg=0.9,
            ev_ebitda=15, ev_sales=2.8, rev_ttm=0.08, rev_fwd=0.25,
            op_mgn=0.11, fcf_y=0.02, div_y=0, beta=1.6,
            high52=110, low52=55, buy=18, hold=6, sell=0,
            pt_low=85, pt_avg=110, pt_high=140,
            rec="BUY", conviction="HIGH", exp_ret=0.29,
            bull=140, base=110, bear=72,
            thesis_summary="800G/1.6T transceiver leader; co-packaged optics roadmap is the longer-term catalyst.",
            thesis=["Vertically integrated optical components", "1.6T ramp drives ASP up", "CPO option value 2027+"],
            risks=["Debt load from II-VI merger", "Cyclical telecom drag"]),
        _co("Lumentum", ticker="LITE", share_pct=18, bucket="10-25",
            moats=["tech"], demand="growing",
            price=72, mcap=4_900_000_000, pe_t=None, pe_f=28, peg=1.5,
            buy=12, hold=10, sell=1, pt_low=68, pt_avg=88, pt_high=110,
            rec="BUY", conviction="MEDIUM", exp_ret=0.22,
            thesis_summary="Pure-play optical components recovery story; smaller scale than Coherent."),
        _co("Innolight", public=False, hq="China", share_pct=28, bucket="25-50",
            moats=["scale"], demand="fast growth in China hyperscalers",
            rec="N/A", thesis_summary="Private — China hyperscaler exposure not investable for Western LPs."),
    ],

    "Datacenter Power & Cooling": [
        _co("Vertiv Holdings", ticker="VRT", share_pct=24, bucket="10-25",
            moats=["scale", "tech"],
            switching="high - integrated into rack/PUE design",
            demand="accelerating - liquid cooling backlog",
            structure="oligopoly", supply="constrained",
            price=110, mcap=42_000_000_000, pe_t=38, pe_f=24, peg=0.9,
            ev_ebitda=22, ev_sales=5.5, rev_ttm=0.18, rev_fwd=0.28,
            op_mgn=0.18, fcf_y=0.022, div_y=0.001, beta=1.5,
            high52=135, low52=70, buy=22, hold=4, sell=0,
            pt_low=110, pt_avg=140, pt_high=175,
            rec="STRONG_BUY", conviction="HIGH", exp_ret=0.27,
            bull=175, base=140, bear=90,
            thesis_summary="Pure-play on the new binding constraint of AI buildout: power & liquid cooling.",
            thesis=[
                "Liquid cooling backlog +60% YoY; 2026 capacity sold out",
                "Highest revenue % from datacenters among power/cooling vendors",
                "Margin expansion from cooling mix shift",
                "Pure-play vs diversified Schneider/Eaton",
            ],
            risks=["Capex sensitive to hyperscaler digestion", "Smaller scale = supply chain risk"],
            catalysts=["Q3 backlog update", "New product cycle on rear-door heat exchangers"]),
        _co("Schneider Electric", ticker="SU.PA", hq="France",
            share_pct=19, bucket="10-25", moats=["scale"],
            demand="strong - power infrastructure shortage",
            structure="oligopoly",
            price=235, mcap=145_000_000_000, pe_t=28, pe_f=24, peg=2.0,
            ev_ebitda=18, ev_sales=3.8, rev_ttm=0.07, rev_fwd=0.10,
            op_mgn=0.17, fcf_y=0.03, div_y=0.018, beta=1.0,
            buy=26, hold=8, sell=1, pt_low=225, pt_avg=270, pt_high=310,
            rec="BUY", conviction="HIGH", exp_ret=0.18,
            bull=310, base=270, bear=210,
            thesis_summary="Diversified power infra with strong datacenter exposure. Defensive AI play."),
        _co("Eaton", ticker="ETN", hq="Ireland", share_pct=14, bucket="10-25",
            moats=["scale"], demand="strong + UPS shortage",
            price=320, mcap=130_000_000_000, pe_t=32, pe_f=27, peg=2.3,
            ev_ebitda=20, ev_sales=4.2, rev_ttm=0.08, rev_fwd=0.11,
            op_mgn=0.19, fcf_y=0.025, div_y=0.012, beta=1.05,
            buy=24, hold=6, sell=1, pt_low=320, pt_avg=375, pt_high=430,
            rec="BUY", conviction="MEDIUM", exp_ret=0.17,
            thesis_summary="Diversified industrial with strong datacenter + grid exposure; high quality compounder."),
    ],

    "Hyperscale Cloud": [
        _co("Microsoft", ticker="MSFT", share_pct=25, bucket="25-50",
            moats=["scale", "tech"], switching="very high",
            demand="accelerating - OpenAI partnership",
            structure="oligopoly",
            price=470, mcap=3_500_000_000_000, pe_t=38, pe_f=32, peg=1.7,
            ev_ebitda=24, ev_sales=14, rev_ttm=0.14, rev_fwd=0.16,
            op_mgn=0.45, fcf_y=0.022, div_y=0.007, beta=0.9,
            high52=510, low52=380, buy=58, hold=4, sell=0,
            pt_low=480, pt_avg=550, pt_high=620,
            rec="BUY", conviction="HIGH", exp_ret=0.18,
            bull=620, base=550, bear=420,
            thesis_summary="Best-positioned hyperscaler given OpenAI exclusivity + Azure AI commitments.",
            thesis=["OpenAI exclusive cloud", "Copilot revenue inflection", "Azure AI revenue ~$10B run-rate"],
            risks=["Capex outpacing FCF in near term", "OpenAI dependency"]),
        _co("Amazon", ticker="AMZN", share_pct=32, bucket="25-50",
            moats=["scale", "tech"], demand="strong, AI workloads growing",
            price=205, mcap=2_150_000_000_000, pe_t=42, pe_f=32, peg=1.5,
            ev_ebitda=18, ev_sales=3.2, rev_ttm=0.11, rev_fwd=0.13,
            op_mgn=0.10, fcf_y=0.025, div_y=0, beta=1.2,
            buy=58, hold=2, sell=0, pt_low=220, pt_avg=265, pt_high=310,
            rec="BUY", conviction="HIGH", exp_ret=0.27,
            bull=310, base=265, bear=180,
            thesis_summary="AWS AI revenue reaccelerating; Bedrock + Trainium are credible alternatives to MSFT/GCP."),
        _co("Alphabet", ticker="GOOGL", share_pct=11, bucket="10-25",
            moats=["tech"], demand="growing - Gemini + TPU pull",
            price=185, mcap=2_300_000_000_000, pe_t=24, pe_f=20, peg=1.4,
            op_mgn=0.31, beta=1.05,
            buy=44, hold=8, sell=1, pt_low=180, pt_avg=215, pt_high=255,
            rec="BUY", conviction="HIGH", exp_ret=0.22),
    ],

    "GPU Neoclouds": [
        _co("CoreWeave", ticker="CRWV", share_pct=40, bucket="25-50",
            moats=["scale"], customer="Microsoft is >60% of revenue",
            demand="+200% YoY contracted backlog",
            structure="oligopoly", supply="constrained",
            price=42, mcap=35_000_000_000, pe_t=None, pe_f=None, peg=None,
            ev_ebitda=24, ev_sales=8, rev_ttm=2.5, rev_fwd=0.75,
            op_mgn=-0.10, fcf_y=-0.15, div_y=0, beta=2.5,
            high52=68, low52=28, buy=14, hold=8, sell=2,
            pt_low=35, pt_avg=55, pt_high=82,
            rec="BUY", conviction="MEDIUM", exp_ret=0.31,
            bull=82, base=55, bear=28,
            thesis_summary="Pure-play GPU rental at scale. Customer concentration on MSFT is the discount.",
            thesis=["NVIDIA-preferred partner with H100/B200 priority allocation", "Backlog visibility through 2027"],
            risks=["Microsoft = 60% customer concentration", "GPU depreciation cycle risk", "Heavy debt load"]),
        _co("Lambda", public=False, share_pct=15, bucket="10-25",
            moats=["tech"], demand="growing - researcher + startup demand",
            val=5_000_000_000, rec="HOLD", conviction="N/A",
            thesis_summary="Private — researcher-focused GPU cloud. Watch for IPO."),
        _co("Crusoe", public=False, share_pct=10, bucket="10-25",
            moats=["scale"], demand="strong - stranded power moat",
            val=2_800_000_000, rec="BUY", conviction="N/A",
            thesis_summary="Private — best moat (stranded power) but unlisted; IPO speculation late-2026."),
    ],

    "Foundation Model Labs": [
        _co("OpenAI", public=False, share_pct=55, bucket="50-75",
            moats=["ip", "scale", "tech"], demand="exponential, $10B+ run-rate",
            val=300_000_000_000, structure="oligopoly", supply="constrained",
            rec="N/A", conviction="N/A",
            thesis_summary="Private. ~$300B valuation implies 30x forward revenue; access via secondary or MSFT proxy."),
        _co("Anthropic", public=False, share_pct=22, bucket="10-25",
            moats=["ip", "tech"], demand="+300% YoY API revenue",
            val=60_000_000_000, structure="oligopoly",
            rec="N/A", conviction="N/A",
            thesis_summary="Private at ~$60B; cleanest pure-play challenger. Access via Anthropic-backed funds or AMZN/GOOGL proxies."),
        _co("Meta Platforms", ticker="META", share_pct=8, bucket="<10",
            moats=["ip", "tech"], demand="Llama OSS strategy",
            price=580, mcap=1_500_000_000_000, pe_t=28, pe_f=23, peg=1.2,
            op_mgn=0.42, fcf_y=0.035, div_y=0.003, beta=1.2,
            buy=52, hold=4, sell=0, pt_low=580, pt_avg=680, pt_high=820,
            rec="BUY", conviction="HIGH", exp_ret=0.20,
            bull=820, base=680, bear=480,
            thesis_summary="Llama 4 + Reality Labs optionality. Capex peak in sight; FCF inflection 2026.",
            thesis=["Llama is the OSS reference model", "AI ad-targeting is real revenue contributor", "Reality Labs optionality"],
            risks=["Reality Labs cash burn", "Regulatory antitrust"]),
    ],

    "Inference Hardware Startups": [
        _co("Groq", public=False, share_pct=4, bucket="<10",
            moats=["ip", "tech"], demand="growing inference customers",
            val=2_800_000_000, rec="N/A"),
        _co("Cerebras", public=False, share_pct=3, bucket="<10",
            moats=["ip", "tech"], val=4_300_000_000, rec="N/A",
            thesis_summary="Filed for IPO; wait for pricing."),
        _co("SambaNova", public=False, share_pct=2, bucket="<10",
            moats=["tech"], val=5_000_000_000, rec="N/A"),
    ],

    "Vector Databases": [
        _co("Pinecone", public=False, share_pct=35, bucket="25-50",
            moats=["tech", "scale"], switching="medium",
            demand="RAG-driven growth", val=750_000_000, rec="N/A"),
        _co("Weaviate", public=False, share_pct=14, bucket="10-25",
            moats=["tech"], val=200_000_000, rec="N/A"),
    ],

    "LLM Observability": [
        _co("LangSmith (LangChain)", public=False, share_pct=30, bucket="25-50",
            moats=["scale"], switching="low - tracing is portable",
            val=1_100_000_000, rec="N/A"),
        _co("Arize AI", public=False, share_pct=14, bucket="10-25",
            moats=["tech"], val=700_000_000, rec="N/A"),
    ],

    "Data Labeling / RLHF": [
        _co("Scale AI", public=False, share_pct=42, bucket="25-50",
            moats=["scale", "tech"], switching="high",
            customer="frontier labs + DoD heavy", demand="strong",
            val=14_000_000_000, rec="N/A",
            thesis_summary="Private at $14B; IPO speculation. DoD revenue de-risks frontier-lab dependency."),
    ],

    "Agent Frameworks": [
        _co("LangChain", public=False, share_pct=45, bucket="25-50",
            moats=["scale"], switching="low - OSS, easy to swap",
            val=1_100_000_000, rec="N/A"),
        _co("LlamaIndex", public=False, share_pct=18, bucket="10-25",
            moats=["tech"], val=220_000_000, rec="N/A"),
    ],

    "Synthetic Data": [
        _co("Gretel.ai", public=False, share_pct=25, bucket="10-25",
            moats=["tech"], val=320_000_000, rec="N/A"),
    ],

    "Edge / On-Device Inference": [
        _co("Qualcomm", ticker="QCOM", share_pct=38, bucket="25-50",
            moats=["ip", "scale"], switching="high - modem+NPU bundle",
            demand="AI PC + AI phone tailwind",
            price=170, mcap=190_000_000_000, pe_t=18, pe_f=15, peg=1.2,
            ev_ebitda=12, ev_sales=4.2, rev_ttm=0.10, rev_fwd=0.13,
            op_mgn=0.28, fcf_y=0.055, div_y=0.020, beta=1.2,
            buy=22, hold=14, sell=1, pt_low=170, pt_avg=200, pt_high=240,
            rec="BUY", conviction="MEDIUM", exp_ret=0.18,
            thesis_summary="AI PC tailwind + Apple modem replacement defense; auto + IoT optionality.",
            thesis=["Snapdragon X for AI PC adoption", "Auto + IoT diversification"],
            risks=["Apple modem in-house transition", "China handset cyclicality"]),
        _co("Apple", ticker="AAPL", share_pct=28, bucket="25-50",
            moats=["ip", "scale", "tech"], demand="captive - all Apple devices",
            price=235, mcap=3_600_000_000_000, pe_t=35, pe_f=30, peg=2.5,
            op_mgn=0.31, fcf_y=0.028, div_y=0.005, beta=1.2,
            buy=32, hold=18, sell=2, pt_low=230, pt_avg=265, pt_high=320,
            rec="HOLD", conviction="MEDIUM", exp_ret=0.12),
        _co("Hailo", public=False, hq="Israel", share_pct=5, bucket="<10",
            moats=["ip", "tech"], val=1_200_000_000, rec="N/A"),
    ],
}


# ---------- earnings power patch (Pass 1) ----------
#
# Hand-crafted illustrative values for the new "Earnings Power & Balance Sheet"
# section. Each entry keyed by company name (must match _co name exactly).
# Numbers are plausible but illustrative (May 2026 cutoff) — not investment advice.
#
# Fields:
#   roic, roic_5y_avg, roic_trend, wacc
#   net_debt_usd  (negative = net cash)
#   debt_to_ebitda, interest_coverage, current_ratio
#   capex_to_sales, capex_guidance_trend
#   fcf_margin_after_capex
#   rd_to_sales, rd_trend
#   buyback_yield, total_shareholder_yield

EARNINGS_POWER: dict[str, dict] = {
    # Materials
    "Freeport-McMoRan": dict(
        roic=0.14, roic_5y_avg=0.09, roic_trend="improving", wacc=0.09,
        net_debt_usd=8_000_000_000, debt_to_ebitda=1.1, interest_coverage=11, current_ratio=2.1,
        capex_to_sales=0.12, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.12, rd_to_sales=0.005, rd_trend="stable",
        buyback_yield=0.015, total_shareholder_yield=0.027,
    ),
    "Southern Copper": dict(
        roic=0.25, roic_5y_avg=0.21, roic_trend="stable", wacc=0.09,
        net_debt_usd=5_000_000_000, debt_to_ebitda=1.0, interest_coverage=18, current_ratio=2.8,
        capex_to_sales=0.15, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.18, rd_to_sales=0.003, rd_trend="stable",
        buyback_yield=0.0, total_shareholder_yield=0.045,
    ),
    "BHP Group": dict(
        roic=0.18, roic_5y_avg=0.17, roic_trend="stable", wacc=0.085,
        net_debt_usd=12_000_000_000, debt_to_ebitda=0.6, interest_coverage=22, current_ratio=1.4,
        capex_to_sales=0.11, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.20, rd_to_sales=0.001, rd_trend="stable",
        buyback_yield=0.01, total_shareholder_yield=0.062,
    ),
    "MP Materials": dict(
        roic=-0.02, roic_5y_avg=0.05, roic_trend="declining", wacc=0.12,
        net_debt_usd=-150_000_000, debt_to_ebitda=2.5, interest_coverage=2.5, current_ratio=4.0,
        capex_to_sales=0.55, capex_guidance_trend="raising",
        fcf_margin_after_capex=-0.30, rd_to_sales=0.06, rd_trend="rising",
        buyback_yield=0.0, total_shareholder_yield=0.0,
    ),
    "Lynas Rare Earths": dict(
        roic=0.10, roic_5y_avg=0.12, roic_trend="declining", wacc=0.11,
        net_debt_usd=-200_000_000, debt_to_ebitda=0.2, interest_coverage=25, current_ratio=3.5,
        capex_to_sales=0.30, capex_guidance_trend="raising",
        fcf_margin_after_capex=-0.05, rd_to_sales=0.025, rd_trend="rising",
        buyback_yield=0.0, total_shareholder_yield=0.0,
    ),
    # Industrial gases
    "Linde": dict(
        roic=0.16, roic_5y_avg=0.14, roic_trend="improving", wacc=0.07,
        net_debt_usd=14_000_000_000, debt_to_ebitda=1.3, interest_coverage=18, current_ratio=0.9,
        capex_to_sales=0.13, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.17, rd_to_sales=0.018, rd_trend="stable",
        buyback_yield=0.025, total_shareholder_yield=0.038,
    ),
    "Air Products": dict(
        roic=0.10, roic_5y_avg=0.12, roic_trend="declining", wacc=0.075,
        net_debt_usd=10_500_000_000, debt_to_ebitda=2.4, interest_coverage=10, current_ratio=1.5,
        capex_to_sales=0.28, capex_guidance_trend="raising",
        fcf_margin_after_capex=-0.05, rd_to_sales=0.012, rd_trend="stable",
        buyback_yield=0.0, total_shareholder_yield=0.025,
    ),
    "Air Liquide": dict(
        roic=0.11, roic_5y_avg=0.10, roic_trend="stable", wacc=0.07,
        net_debt_usd=12_500_000_000, debt_to_ebitda=1.8, interest_coverage=15, current_ratio=1.0,
        capex_to_sales=0.13, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.10, rd_to_sales=0.015, rd_trend="stable",
        buyback_yield=0.005, total_shareholder_yield=0.024,
    ),
    # Specialty chemicals
    "Shin-Etsu Chemical": dict(
        roic=0.18, roic_5y_avg=0.16, roic_trend="improving", wacc=0.08,
        net_debt_usd=-5_000_000_000, debt_to_ebitda=0.0, interest_coverage=80, current_ratio=4.0,
        capex_to_sales=0.10, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.22, rd_to_sales=0.055, rd_trend="rising",
        buyback_yield=0.018, total_shareholder_yield=0.036,
    ),
    "JSR Corporation": dict(
        roic=0.10, roic_5y_avg=0.09, roic_trend="stable", wacc=0.085,
        net_debt_usd=1_000_000_000, debt_to_ebitda=1.5, interest_coverage=8, current_ratio=2.0,
        capex_to_sales=0.10, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.07, rd_to_sales=0.075, rd_trend="rising",
        buyback_yield=0.005, total_shareholder_yield=0.030,
    ),
    "Entegris": dict(
        roic=0.08, roic_5y_avg=0.12, roic_trend="declining", wacc=0.09,
        net_debt_usd=4_700_000_000, debt_to_ebitda=3.5, interest_coverage=4, current_ratio=2.5,
        capex_to_sales=0.09, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.06, rd_to_sales=0.045, rd_trend="stable",
        buyback_yield=0.0, total_shareholder_yield=0.006,
    ),
    # Substrates
    "Ibiden": dict(
        roic=0.13, roic_5y_avg=0.11, roic_trend="improving", wacc=0.08,
        net_debt_usd=-500_000_000, debt_to_ebitda=0.0, interest_coverage=50, current_ratio=2.5,
        capex_to_sales=0.28, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.05, rd_to_sales=0.025, rd_trend="rising",
        buyback_yield=0.01, total_shareholder_yield=0.023,
    ),
    "Unimicron": dict(
        roic=0.11, roic_5y_avg=0.10, roic_trend="stable", wacc=0.09,
        net_debt_usd=800_000_000, debt_to_ebitda=1.2, interest_coverage=10, current_ratio=2.0,
        capex_to_sales=0.22, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.04, rd_to_sales=0.020, rd_trend="stable",
        buyback_yield=0.0, total_shareholder_yield=0.022,
    ),
    "Shinko Electric": dict(
        roic=0.09, roic_5y_avg=0.10, roic_trend="stable", wacc=0.085,
        net_debt_usd=-300_000_000, debt_to_ebitda=0.0, interest_coverage=30, current_ratio=2.8,
        capex_to_sales=0.20, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.04, rd_to_sales=0.025, rd_trend="stable",
        buyback_yield=0.0, total_shareholder_yield=0.025,
    ),
    # Water
    "Xylem": dict(
        roic=0.11, roic_5y_avg=0.10, roic_trend="improving", wacc=0.08,
        net_debt_usd=2_200_000_000, debt_to_ebitda=1.5, interest_coverage=14, current_ratio=2.0,
        capex_to_sales=0.04, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.12, rd_to_sales=0.030, rd_trend="stable",
        buyback_yield=0.0, total_shareholder_yield=0.010,
    ),
    "Pentair": dict(
        roic=0.13, roic_5y_avg=0.11, roic_trend="stable", wacc=0.085,
        net_debt_usd=1_500_000_000, debt_to_ebitda=1.7, interest_coverage=12, current_ratio=1.5,
        capex_to_sales=0.025, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.14, rd_to_sales=0.020, rd_trend="stable",
        buyback_yield=0.018, total_shareholder_yield=0.037,
    ),
    # Semi capex
    "ASML Holding": dict(
        roic=0.48, roic_5y_avg=0.42, roic_trend="improving", wacc=0.08,
        net_debt_usd=-4_500_000_000, debt_to_ebitda=0.0, interest_coverage=200, current_ratio=2.5,
        capex_to_sales=0.10, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.25, rd_to_sales=0.13, rd_trend="rising",
        buyback_yield=0.012, total_shareholder_yield=0.020,
    ),
    "TSMC": dict(
        roic=0.27, roic_5y_avg=0.22, roic_trend="improving", wacc=0.08,
        net_debt_usd=-30_000_000_000, debt_to_ebitda=0.0, interest_coverage=150, current_ratio=2.4,
        capex_to_sales=0.41, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.10, rd_to_sales=0.085, rd_trend="rising",
        buyback_yield=0.0, total_shareholder_yield=0.013,
    ),
    "Samsung Foundry": dict(
        roic=0.09, roic_5y_avg=0.13, roic_trend="declining", wacc=0.085,
        net_debt_usd=-40_000_000_000, debt_to_ebitda=0.0, interest_coverage=100, current_ratio=2.5,
        capex_to_sales=0.16, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.05, rd_to_sales=0.09, rd_trend="rising",
        buyback_yield=0.0, total_shareholder_yield=0.025,
    ),
    "Intel Foundry": dict(
        roic=-0.04, roic_5y_avg=0.06, roic_trend="declining", wacc=0.10,
        net_debt_usd=24_000_000_000, debt_to_ebitda=4.5, interest_coverage=2, current_ratio=1.5,
        capex_to_sales=0.25, capex_guidance_trend="raising",
        fcf_margin_after_capex=-0.10, rd_to_sales=0.16, rd_trend="rising",
        buyback_yield=0.0, total_shareholder_yield=0.0,
    ),
    "TSMC (CoWoS)": dict(  # Refers user back to TSM parent
        roic=0.27, roic_trend="improving",
    ),
    "Amkor Technology": dict(
        roic=0.10, roic_5y_avg=0.10, roic_trend="stable", wacc=0.09,
        net_debt_usd=-100_000_000, debt_to_ebitda=0.0, interest_coverage=20, current_ratio=2.5,
        capex_to_sales=0.20, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.04, rd_to_sales=0.02, rd_trend="stable",
        buyback_yield=0.01, total_shareholder_yield=0.035,
    ),
    # Silicon
    "NVIDIA": dict(
        roic=0.82, roic_5y_avg=0.55, roic_trend="improving", wacc=0.10,
        net_debt_usd=-30_000_000_000, debt_to_ebitda=0.0, interest_coverage=350, current_ratio=4.0,
        capex_to_sales=0.03, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.50, rd_to_sales=0.18, rd_trend="rising",
        buyback_yield=0.014, total_shareholder_yield=0.017,
    ),
    "AMD": dict(
        roic=0.12, roic_5y_avg=0.20, roic_trend="declining", wacc=0.10,
        net_debt_usd=-5_500_000_000, debt_to_ebitda=0.0, interest_coverage=80, current_ratio=2.6,
        capex_to_sales=0.03, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.18, rd_to_sales=0.22, rd_trend="rising",
        buyback_yield=0.008, total_shareholder_yield=0.008,
    ),
    "Google TPU": dict(
        roic=0.26, roic_5y_avg=0.24, roic_trend="stable", wacc=0.085,
        net_debt_usd=-95_000_000_000, debt_to_ebitda=0.0, interest_coverage=300, current_ratio=2.0,
        capex_to_sales=0.18, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.20, rd_to_sales=0.14, rd_trend="rising",
        buyback_yield=0.022, total_shareholder_yield=0.027,
    ),
    # Memory
    "SK Hynix": dict(
        roic=0.20, roic_5y_avg=0.13, roic_trend="improving", wacc=0.10,
        net_debt_usd=18_000_000_000, debt_to_ebitda=1.8, interest_coverage=12, current_ratio=1.8,
        capex_to_sales=0.27, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.12, rd_to_sales=0.085, rd_trend="rising",
        buyback_yield=0.005, total_shareholder_yield=0.017,
    ),
    "Micron": dict(
        roic=0.15, roic_5y_avg=0.10, roic_trend="improving", wacc=0.10,
        net_debt_usd=8_000_000_000, debt_to_ebitda=1.6, interest_coverage=11, current_ratio=3.0,
        capex_to_sales=0.30, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.05, rd_to_sales=0.11, rd_trend="rising",
        buyback_yield=0.0, total_shareholder_yield=0.005,
    ),
    # Networking
    "Broadcom": dict(
        roic=0.21, roic_5y_avg=0.22, roic_trend="stable", wacc=0.085,
        net_debt_usd=68_000_000_000, debt_to_ebitda=3.0, interest_coverage=8, current_ratio=1.3,
        capex_to_sales=0.02, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.42, rd_to_sales=0.16, rd_trend="stable",
        buyback_yield=0.018, total_shareholder_yield=0.030,
    ),
    "Marvell": dict(
        roic=0.05, roic_5y_avg=0.07, roic_trend="stable", wacc=0.10,
        net_debt_usd=3_800_000_000, debt_to_ebitda=4.8, interest_coverage=4, current_ratio=1.6,
        capex_to_sales=0.04, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.15, rd_to_sales=0.30, rd_trend="rising",
        buyback_yield=0.01, total_shareholder_yield=0.013,
    ),
    "Coherent": dict(
        roic=0.04, roic_5y_avg=0.06, roic_trend="declining", wacc=0.10,
        net_debt_usd=5_500_000_000, debt_to_ebitda=6.0, interest_coverage=2, current_ratio=2.0,
        capex_to_sales=0.06, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.05, rd_to_sales=0.10, rd_trend="rising",
        buyback_yield=0.0, total_shareholder_yield=0.0,
    ),
    "Lumentum": dict(
        roic=-0.02, roic_5y_avg=0.05, roic_trend="declining", wacc=0.11,
        net_debt_usd=1_200_000_000, debt_to_ebitda=8.0, interest_coverage=2, current_ratio=4.0,
        capex_to_sales=0.05, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.02, rd_to_sales=0.18, rd_trend="stable",
        buyback_yield=0.0, total_shareholder_yield=0.0,
    ),
    # Power & cooling
    "Vertiv Holdings": dict(
        roic=0.20, roic_5y_avg=0.12, roic_trend="improving", wacc=0.09,
        net_debt_usd=2_000_000_000, debt_to_ebitda=1.5, interest_coverage=14, current_ratio=1.8,
        capex_to_sales=0.03, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.16, rd_to_sales=0.03, rd_trend="stable",
        buyback_yield=0.005, total_shareholder_yield=0.006,
    ),
    "Schneider Electric": dict(
        roic=0.15, roic_5y_avg=0.13, roic_trend="improving", wacc=0.075,
        net_debt_usd=9_000_000_000, debt_to_ebitda=1.4, interest_coverage=15, current_ratio=1.2,
        capex_to_sales=0.03, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.14, rd_to_sales=0.05, rd_trend="rising",
        buyback_yield=0.005, total_shareholder_yield=0.023,
    ),
    "Eaton": dict(
        roic=0.16, roic_5y_avg=0.13, roic_trend="improving", wacc=0.08,
        net_debt_usd=8_500_000_000, debt_to_ebitda=1.7, interest_coverage=14, current_ratio=1.4,
        capex_to_sales=0.03, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.16, rd_to_sales=0.035, rd_trend="stable",
        buyback_yield=0.015, total_shareholder_yield=0.027,
    ),
    # Hyperscale clouds
    "Microsoft": dict(
        roic=0.30, roic_5y_avg=0.27, roic_trend="stable", wacc=0.08,
        net_debt_usd=-50_000_000_000, debt_to_ebitda=0.0, interest_coverage=180, current_ratio=1.7,
        capex_to_sales=0.20, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.25, rd_to_sales=0.13, rd_trend="stable",
        buyback_yield=0.012, total_shareholder_yield=0.019,
    ),
    "Amazon": dict(
        roic=0.13, roic_5y_avg=0.10, roic_trend="improving", wacc=0.085,
        net_debt_usd=-30_000_000_000, debt_to_ebitda=0.0, interest_coverage=80, current_ratio=1.0,
        capex_to_sales=0.15, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.06, rd_to_sales=0.14, rd_trend="rising",
        buyback_yield=0.0, total_shareholder_yield=0.0,
    ),
    "Alphabet": dict(
        roic=0.26, roic_5y_avg=0.24, roic_trend="stable", wacc=0.085,
        net_debt_usd=-95_000_000_000, debt_to_ebitda=0.0, interest_coverage=300, current_ratio=2.0,
        capex_to_sales=0.18, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.20, rd_to_sales=0.14, rd_trend="rising",
        buyback_yield=0.022, total_shareholder_yield=0.027,
    ),
    # Neoclouds
    "CoreWeave": dict(
        roic=-0.08, roic_5y_avg=None, roic_trend="declining", wacc=0.13,
        net_debt_usd=15_000_000_000, debt_to_ebitda=8.0, interest_coverage=1.2, current_ratio=1.1,
        capex_to_sales=1.20, capex_guidance_trend="raising",
        fcf_margin_after_capex=-0.45, rd_to_sales=0.04, rd_trend="stable",
        buyback_yield=0.0, total_shareholder_yield=0.0,
    ),
    # Models
    "Meta Platforms": dict(
        roic=0.27, roic_5y_avg=0.22, roic_trend="improving", wacc=0.09,
        net_debt_usd=-30_000_000_000, debt_to_ebitda=0.0, interest_coverage=120, current_ratio=2.5,
        capex_to_sales=0.17, capex_guidance_trend="raising",
        fcf_margin_after_capex=0.22, rd_to_sales=0.28, rd_trend="rising",
        buyback_yield=0.020, total_shareholder_yield=0.023,
    ),
    # Edge
    "Qualcomm": dict(
        roic=0.27, roic_5y_avg=0.22, roic_trend="stable", wacc=0.085,
        net_debt_usd=2_000_000_000, debt_to_ebitda=0.3, interest_coverage=30, current_ratio=2.7,
        capex_to_sales=0.04, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.24, rd_to_sales=0.19, rd_trend="stable",
        buyback_yield=0.018, total_shareholder_yield=0.038,
    ),
    "Apple": dict(
        roic=0.55, roic_5y_avg=0.42, roic_trend="improving", wacc=0.085,
        net_debt_usd=-60_000_000_000, debt_to_ebitda=0.0, interest_coverage=200, current_ratio=1.0,
        capex_to_sales=0.025, capex_guidance_trend="stable",
        fcf_margin_after_capex=0.27, rd_to_sales=0.08, rd_trend="rising",
        buyback_yield=0.030, total_shareholder_yield=0.035,
    ),
}


# ---------- public helpers ----------

def evidence_for(company_name: str, component: str) -> list[dict]:
    """Plausible-looking evidence rows for a mock company."""
    return [
        {
            "claim": f"{company_name} holds a leading position in {component}.",
            "source_url": f"https://example.com/research/{component.lower().replace(' ', '-')}",
            "source_name": "web",
            "tool_name": "web_search",
            "snippet": f"Industry analysts cite {company_name} as a key player in {component}.",
        },
        {
            "claim": f"Recent filings support market position for {company_name}.",
            "source_url": f"https://example.com/filings/{(company_name.split()[0] if company_name else 'co').lower()}-10k",
            "source_name": "web",
            "tool_name": "web_fetch",
            "snippet": "10-K disclosure cited.",
        },
    ]


def findings_for_component(component_name: str) -> list[dict]:
    base = MOCK_FINDINGS.get(component_name)
    if not base:
        return [
            {
                "name": f"Leader (mock) for {component_name}",
                "is_public": True, "ticker": "TBD",
                "market_share_pct": 45.0, "market_share_bucket": "25-50",
                "single_source": False, "moat_types": ["scale"],
                "switching_costs": "medium", "demand_signal": "growing",
                "valuation_usd": None, "notes": "Generic mock placeholder.",
                "extras": {"recommendation": "HOLD"},
            }
        ]
    enriched = []
    for c in base:
        c2 = dict(c)
        c2.setdefault("evidence", evidence_for(c["name"], component_name))
        # Merge in the earnings-power patch if we have hand-crafted data for this name.
        patch = EARNINGS_POWER.get(c["name"])
        if patch:
            extras = dict(c2.get("extras") or {})
            for k, v in patch.items():
                if v is not None and k not in extras:
                    extras[k] = v
                elif v is not None:
                    extras[k] = v
            c2["extras"] = extras
        enriched.append(c2)
    return enriched
